# Generated by Django 2.0.3 on 2018-04-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(unique=True)),
                ('iscontrol', models.BooleanField(default=True)),
                ('lastlogin', models.DateTimeField(verbose_name='lastlogin')),
            ],
        ),
    ]
