# Generated by Django 2.0.3 on 2018-04-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_user_id', models.IntegerField()),
                ('submit_time', models.DateTimeField()),
                ('q1', models.IntegerField(default=-1)),
                ('q2', models.IntegerField(default=-1)),
                ('q3', models.IntegerField(default=-1)),
                ('q4', models.IntegerField(default=-1)),
                ('q5', models.IntegerField(default=-1)),
                ('q6', models.IntegerField(default=-1)),
                ('q7', models.IntegerField(default=-1)),
                ('q8', models.IntegerField(default=-1)),
                ('q9', models.IntegerField(default=-1)),
                ('q10', models.IntegerField(default=-1)),
                ('q11', models.IntegerField(default=-1)),
                ('q12', models.IntegerField(default=-1)),
                ('q13', models.IntegerField(default=-1)),
                ('q14', models.IntegerField(default=-1)),
                ('q15', models.IntegerField(default=-1)),
                ('q16', models.IntegerField(default=-1)),
                ('q17', models.IntegerField(default=-1)),
                ('q18', models.IntegerField(default=-1)),
                ('q19', models.IntegerField(default=-1)),
                ('q20', models.IntegerField(default=-1)),
                ('q21', models.IntegerField(default=-1)),
                ('q22', models.IntegerField(default=-1)),
                ('q23', models.IntegerField(default=-1)),
                ('q24', models.IntegerField(default=-1)),
                ('q25', models.IntegerField(default=-1)),
                ('q26', models.IntegerField(default=-1)),
                ('q27', models.IntegerField(default=-1)),
                ('q28', models.IntegerField(default=-1)),
                ('q29', models.IntegerField(default=-1)),
                ('q30', models.IntegerField(default=-1)),
                ('q31', models.IntegerField(default=-1)),
                ('q32', models.IntegerField(default=-1)),
                ('q33', models.IntegerField(default=-1)),
                ('q34', models.IntegerField(default=-1)),
                ('q35', models.IntegerField(default=-1)),
                ('q36', models.IntegerField(default=-1)),
            ],
        ),
    ]
