# Generated by Django 2.0.3 on 2018-05-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
