# Generated by Django 2.0.3 on 2018-05-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180516_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='ping_type',
            field=models.IntegerField(default=0),
        ),
    ]
