# Generated by Django 2.0.3 on 2018-06-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_checkin_ping_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCompactResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_user_id', models.IntegerField()),
                ('submit_time', models.DateTimeField()),
                ('answer_sequence', models.CharField(max_length=128)),
            ],
        ),
    ]
