# Generated by Django 2.0.3 on 2018-06-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180615_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('week', models.IntegerField()),
                ('avg_weight', models.FloatField()),
                ('avg_steps', models.FloatField()),
                ('total_active_min', models.IntegerField()),
                ('height', models.FloatField()),
            ],
        ),
    ]
